### ISSUE TITLE
.

### ISSUE THREAD

**Issue by karlisadams** [skibblenybbles/PinterestPlus#4] opened 2013-09-25 07:13 UTC
.

**Comment by skibblenybbles** [comment] 2013-10-24 16:20
This issues used to read "Doesn't work now." I've finally had some time to look into this. The example HTML files demonstrate usage of the PinterestPlus button implementation, and they still seem to be working fine. I'm closing this issue, as I can't reproduce it.

**Closed as completed by skibblenybbles** 2013-10-24 16:20 UTC
